[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = nrf24/RF24@^1.4.9

[env:tx]
build_src_filter = +<tx/>
upload_port = COM3
monitor_port = COM3

[env:rx]
build_src_filter = +<rx/>
upload_port = COM4
monitor_port = COM4

# pio run -e tx -t upload
